[keyboard]
name = "Flow Keyboard"
product_name = "Flow Keyboard"
vendor_id = 0x0408
product_id = 0x0001
manufacturer = "Licardo"
chip = "nrf52840"

[matrix]
# Row and col pins are mandatory
row_pins = ["P1_00"]
col_pins = ["P0_15", "P0_06", "P0_04", "P0_26"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 1
cols = 4
layers = 1
matrix_map = """
(0,0) (0,1) (0,2) (0,3)
"""

[[input_device.encoder]]
pin_a = "P1_09"
pin_b = "P0_08"

# Whether to use the MCU's internal pull-up resistor, default to false
internal_pullup = false

# Working mode of the encoder
# Available modes:
# - default: resolution = 1
# - resolution: custom resolution, requires specifying resolution and reverse parameters
phase = "resolution"

# `resolution` represents the number of steps generated per detent.
#
# When your encoder datasheet lists:
#   - detent = number of mechanical detent positions  
#   - pulse  = number of full quadrature cycles (A/B cycles)  
#
# Then the relationship is:
#   resolution = (pulse × 4) / detent
# because each full quadrature cycle (pulse) produces 4 edge transitions.
#
# For example — in the ALPS EC11E series(https://tech.alpsalpine.com/cms.media/product_catalog_ec_01_ec11e_en_611f078659.pdf):
#   detent = 30, pulse = 15 → resolution = (15 × 4) / 30 = 2
resolution = 4

# Whether the direction of the rotary encoder is reversed.
reverse = false

[storage]
# Storage feature is enabled by default
# enabled = false
# clear_storage = true

[ble]
enabled = true
# vddh has an internal voltage divider
#battery_adc_pin = "vddh"
# Or
battery_adc_pin = "P0_04"
adc_divider_measured = 10000
adc_divider_total = 20000
