[keyboard]
name = "Flow Keyboard"
product_name = "Flow Keyboard"
vendor_id = 0x0408
product_id = 0x0001
manufacturer = "Licardo"
chip = "nrf52840"

[matrix]
# Row and col pins are mandatory
row_pins = ["P1_00"]
col_pins = ["P0_15", "P0_06", "P0_04", "P0_26"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 1
cols = 4
layers = 1
matrix_map = """
(0,0) (0,1) (0,2) (0,3)
"""

[[layer]]
name = "base_layer"
keys = """
Kp0     Kp1     Kp2     Kp3
"""

[[input_device.encoder]]
pin_a = "P1_09"
pin_b = "P0_08"

[storage]
# Storage feature is enabled by default
# enabled = false
# clear_storage = true

[ble]
enabled = true
# vddh has an internal voltage divider
#battery_adc_pin = "vddh"
# Or
battery_adc_pin = "P0_04"
adc_divider_measured = 10000
adc_divider_total = 20000
